import torch
from EXACT.utils import predict_proba_fn
from lime.lime_text import LimeTextExplainer


class LimeExplainer_Text:

    '''
    Lime Text Explainer for Exact Library 

    Responsibilities
        - Generate LIME explanations for text models
        - Support token-id based Pytorch models
        - Returns raw explanation data
        - Optional visualization utilities
    
    '''

    def __init__(self, model, tokenizer, class_names = None, num_samples = 5000, random_state = 42):
        '''
        Parameters
        -----------

        model : torch.nn.Module
            Trained PyTorch text classification model

        tokenizer : callable
            Function that converts list[str] -> tensor input for model

        class_names : list[str], optional
            Names of output classes

        num_samples : int
            Number of perturbed samples generated by LIME 

        random_state : int
            Seed for reproducibility
        
        '''

        self.model = model
        self.tokenizer = tokenizer
        self.class_names = class_names
        self.num_samples = num_samples

        self.explainer = LimeTextExplainer(class_names=class_names, random_state=random_state)

        self.device = next(model.parameters()).device

    # ------------------------- Core explanation logic -------------------------

    def explain(self, text, top_labels = 1):
        '''
        Generate a LIME Explanation for a single text input.

        Parameters
        -----------
        text : str
            Input text
        
        top_labels : int
            Number of top predicted classes to explain

        Returns
        --------
        explanation : lime.explanation.Explanation
            Lime explanation object
        '''

        def predict_fn(texts):
            '''
            Lime passes List[str]
            '''

            self.model.eval()

            # Tokenize texts -> tensor
            model_inputs = self.tokenizer(texts)

            # Ensure tensor
            if isinstance(model_inputs,torch.Tensor):
                model_inputs = model_inputs.to(self.device)

            elif isinstance(model_inputs, dict) or hasattr(model_inputs, "items"):
                model_inputs = {
                    k : v.to(self.device) if isinstance(v, torch.Tensor) else v
                    for k, v in model_inputs.items()
                }

            else:
                raise ValueError("Tokenizer must return a torch.Tensor or Dict[str, torch.Tensor]")


            return predict_proba_fn.predict_proba(model_inputs, model = self.model)
        
        explanation = self.explainer.explain_instance(
            text_instance = text,
            classifier_fn=predict_fn,
            top_labels = top_labels,
            num_samples = self.num_samples
        )

        return explanation 
    
    # ------------------------- Raw explanation data (No plotting) -------------------------

    def get_explanation_data(self, explanation, label = None, num_features = 10):
        '''
        Extract word-level importance scores.

        Parameters
        ----------
        explanation : lime.explanation.Explanation

        label : int, optional
            Class label (defaults to top predicted)

        num_features : int
            Number of words to return

        Returns
        -------
        list of (word, importance)
        '''

        if label is None:
            label = explanation.top_labels[0]

        return explanation.as_list(label = label)[:num_features]
    
    # ------------------------- Optional visualization utility -------------------------

    def visualize(self, explanation, label = None, num_features = 10):
        '''
        Print word importance scores in readable format.
        
        ''' 
        if label is None:
            label = explanation.top_labels[0]


        word_scores = self.get_explanation_data(
            explanation,
            label = label,
            num_features = num_features
            )
        # ---------------- Print predicted class ----------------

        if self.class_names is not None:
            print(f"\nPredicted Class: {self.class_names[label]}")
        else:
            print(f"\nPredicted Class Index: {label}")

        print("\nLIME Text Explanation\n" + "-" * 30)

        for word, score in word_scores:
            sign = '+' if score > 0 else '-'
            print(f"{word:15s} {sign} {abs(score):.4f}")

        return word_scores